# Generated by Django 3.0 on 2019-12-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_title', models.CharField(default='', max_length=50)),
                ('blog_desc', models.CharField(default='', max_length=300)),
                ('heading0', models.CharField(default='', max_length=50)),
                ('content0', models.CharField(default='', max_length=5000)),
                ('heading1', models.CharField(default='', max_length=50)),
                ('content1', models.CharField(default='', max_length=5000)),
                ('heading2', models.CharField(default='', max_length=50)),
                ('content2', models.CharField(default='', max_length=5000)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(default='', upload_to='blog/images')),
            ],
        ),
    ]
